apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: tunnel-router
  name: tunnel-router
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: tunnel-router
    spec:
      hostNetwork: true
      # Needed to inject network interfaces into pods
      hostPID: true
      # Needed to communicate with docker for network NS resolution
      hostIPC: true
      containers:
        - image: bluecmd/tunnel-router
          env:
            - name: TUNNEL_ROUTER_MODE
              value: 'gre'
          imagePullPolicy: Always
          name: router
          securityContext:
            privileged: true
          volumeMounts:
            - name: run
              mountPath: /var/run/docker.sock
      volumes:
        - name: run
          hostPath:
            path: /var/run/docker.sock
      terminationGracePeriodSeconds: 5
