apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: tunnel-router
  name: tunnel-router
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        cmd.nu/tunnel-router: ""
      labels:
        k8s-app: tunnel-router
    spec:
      hostNetwork: true
      containers:
        - args:
          - sleep
          - "10000"
          image: ubuntu:yakkety
          imagePullPolicy: Always
          name: router
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 5
