apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: tunnel-router
  name: tunnel-router
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: tunnel-router
    spec:
      hostNetwork: true
      containers:
        - image: bluecmd/tunnel-router
          imagePullPolicy: Always
          name: router
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 5
